name: Deploy to Neocities and Nekoweb

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-sites
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
      api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
      cleanup: true
      preview_before_deploy: false
      dist_dir: .

    - name: Deploy to Nekoweb
      uses: indiefellas/deploy2nekoweb@main
      with:
        nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
        nekoweb-domain: 'oceanthunder.nekoweb.org'
        nekoweb-username: 'oceanthunder'
        directory: '.'
